### get persons
GET http://localhost:3001/api/persons

### get info
GET http://localhost:3001/info

### get person
GET http://localhost:3001/api/persons/6267a20a4b3bcf96dfe421ad

### delete person
DELETE http://localhost:3001/api/persons/3

### post person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Hellas",
    "number": "33-111222"
}

### update person
PUT http://localhost:3001/api/persons/6267a20a4b3bcf96dfe421ad
Content-Type: application/json

{
    "name": "wizard Howl",
    "number": "999999"
}

### request made to non-existent route
POST http://localhost:3001/api/persons/person
Content-Type: application/json

{
    "name": "tesT",
    "number": "111111"
}


#######################################################################


### heroku get persons

GET https://zeb-phonebook.herokuapp.com/api/persons

### heroku get info
GET https://zeb-phonebook.herokuapp.com/info

### heroku get person
GET https://zeb-phonebook.herokuapp.com/api/persons/2

### heroku delete person
DELETE https://zeb-phonebook.herokuapp.com/api/persons/3

### heroku post person
POST https://zeb-phonebook.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "tesT",
    "number": "111111"
}

### heroku request made to non-existent route
POST https://zeb-phonebook.herokuapp.com/api/persons/person
Content-Type: application/json

{
    "name": "tesT",
    "number": "111111"
}